# Generated by Django 4.0.2 on 2022-03-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0004_alter_empleado_options_alter_empleado_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='cedula',
            field=models.IntegerField(null=True),
        ),
    ]
