# Generated by Django 4.0.2 on 2022-03-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0011_alter_empleado_sueldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
